// Shared utilities for analytics + reports: CSV/PDF generation, COGS estimation, GST math.
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

// ─── CSV ───────────────────────────────────────────────────────────────────
export function downloadCSV(filename: string, rows: (string | number)[][]) {
  const escape = (v: string | number) => {
    const s = String(v ?? "");
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const csv = rows.map((r) => r.map(escape).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── PDF helpers ───────────────────────────────────────────────────────────
export interface PdfReportOptions {
  title: string;
  subtitle?: string;
  hotelName?: string;
  periodLabel?: string;
  summary?: { label: string; value: string }[];
  tables: {
    head: string[];
    body: (string | number)[][];
    title?: string;
  }[];
  footer?: string;
}

export function generatePdfReport(opts: PdfReportOptions): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const ORANGE: [number, number, number] = [249, 115, 22];
  const NAVY: [number, number, number] = [10, 15, 30];
  const MUTED: [number, number, number] = [100, 116, 139];

  // Header bar
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setFillColor(...ORANGE);
  doc.rect(0, 70, pageWidth, 4, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("SpeedoBill", 40, 35);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(opts.hotelName || "Restaurant Report", 40, 52);

  doc.setFontSize(9);
  doc.text(format(new Date(), "dd MMM yyyy, hh:mm a"), pageWidth - 40, 35, { align: "right" });
  if (opts.periodLabel) {
    doc.text(opts.periodLabel, pageWidth - 40, 52, { align: "right" });
  }

  // Title block
  let y = 100;
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(opts.title, 40, y);
  y += 8;
  if (opts.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    doc.text(opts.subtitle, 40, y + 12);
    y += 18;
  }
  y += 15;

  // Summary cards
  if (opts.summary?.length) {
    const cardW = (pageWidth - 80 - (opts.summary.length - 1) * 10) / opts.summary.length;
    opts.summary.forEach((s, i) => {
      const x = 40 + i * (cardW + 10);
      doc.setFillColor(245, 247, 250);
      doc.roundedRect(x, y, cardW, 56, 6, 6, "F");
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.setFont("helvetica", "normal");
      doc.text(s.label.toUpperCase(), x + 10, y + 18);
      doc.setFontSize(13);
      doc.setTextColor(...NAVY);
      doc.setFont("helvetica", "bold");
      doc.text(s.value, x + 10, y + 40);
    });
    y += 70;
  }

  // Tables
  opts.tables.forEach((t) => {
    if (t.title) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(...NAVY);
      doc.text(t.title, 40, y);
      y += 12;
    }
    autoTable(doc, {
      head: [t.head],
      body: t.body.map((row) => row.map((c) => String(c))),
      startY: y,
      theme: "striped",
      headStyles: { fillColor: ORANGE, textColor: 255, fontSize: 9, fontStyle: "bold" },
      bodyStyles: { fontSize: 9, textColor: NAVY },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 40, right: 40 },
    });
    // @ts-expect-error lastAutoTable
    y = (doc.lastAutoTable?.finalY ?? y) + 25;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(
      opts.footer || "Generated by SpeedoBill • speedobill.lovable.app",
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 20,
      { align: "center" }
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 40, doc.internal.pageSize.getHeight() - 20, { align: "right" });
  }

  return doc;
}

export function downloadPdf(doc: jsPDF, filename: string) {
  doc.save(filename);
}

// ─── COGS estimation ───────────────────────────────────────────────────────
// Estimates per-menu-item cost using recipes (ingredient_id → qty_required)
// joined with average unit price from purchase_logs.
export interface RecipeRow {
  menu_item_id: string;
  ingredient_id: string;
  quantity_required: number;
}
export interface PurchaseRow {
  ingredient_id: string;
  unit_price: number;
  quantity: number;
}
export interface MenuItemRow {
  id: string;
  name: string;
  price: number;
  category: string;
}

export function estimateMenuItemCosts(
  menuItems: MenuItemRow[],
  recipes: RecipeRow[],
  purchases: PurchaseRow[]
): Record<string, { cost: number; margin: number }> {
  // avg unit price per ingredient (weighted)
  const ingPrice: Record<string, { totalCost: number; totalQty: number }> = {};
  purchases.forEach((p) => {
    const cur = ingPrice[p.ingredient_id] || { totalCost: 0, totalQty: 0 };
    cur.totalCost += Number(p.unit_price) * Number(p.quantity);
    cur.totalQty += Number(p.quantity);
    ingPrice[p.ingredient_id] = cur;
  });
  const avgPrice: Record<string, number> = {};
  Object.entries(ingPrice).forEach(([k, v]) => {
    avgPrice[k] = v.totalQty > 0 ? v.totalCost / v.totalQty : 0;
  });

  // sum recipe cost per menu item
  const itemCost: Record<string, number> = {};
  recipes.forEach((r) => {
    const c = (avgPrice[r.ingredient_id] || 0) * Number(r.quantity_required);
    itemCost[r.menu_item_id] = (itemCost[r.menu_item_id] || 0) + c;
  });

  const result: Record<string, { cost: number; margin: number }> = {};
  menuItems.forEach((mi) => {
    const cost = itemCost[mi.id] || 0;
    const margin = mi.price > 0 && cost > 0 ? ((mi.price - cost) / mi.price) * 100 : 0;
    result[mi.name] = { cost, margin };
  });
  return result;
}

// ─── GST math (Indian) ─────────────────────────────────────────────────────
// Default split: CGST 2.5% + SGST 2.5% (intra-state) for total 5%.
// We treat all orders as intra-state by default (no IGST) since hotels typically serve locally.
export function calculateGST(total: number, gstPercent: number = 5) {
  const taxable = total / (1 + gstPercent / 100);
  const tax = total - taxable;
  return {
    taxable: Math.round(taxable * 100) / 100,
    cgst: Math.round((tax / 2) * 100) / 100,
    sgst: Math.round((tax / 2) * 100) / 100,
    igst: 0,
    total_tax: Math.round(tax * 100) / 100,
    gross: total,
  };
}

export function fmtINR(n: number) {
  return "₹" + (n || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 });
}
