[build]
  command = "npx vite build --mode production"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_PREFLIGHT_CHECK = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
